# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(574, 718)
        Dialog.setMaximumSize(QSize(574, 718))
        self.layer1 = QFrame(Dialog)
        self.layer1.setObjectName(u"layer1")
        self.layer1.setGeometry(QRect(0, 0, 577, 721))
        self.layer1.setAutoFillBackground(False)
        self.layer1.setStyleSheet(u"background-color: rgb(179, 179, 179);")
        self.layer1.setFrameShape(QFrame.StyledPanel)
        self.layer1.setFrameShadow(QFrame.Raised)
        self.layer2 = QFrame(self.layer1)
        self.layer2.setObjectName(u"layer2")
        self.layer2.setGeometry(QRect(12, 33, 550, 676))
        self.layer2.setAutoFillBackground(False)
        self.layer2.setStyleSheet(u"background-color: rgb(51, 51, 0);\n"
"color: rgb(255, 255, 255);")
        self.layer2.setFrameShape(QFrame.VLine)
        self.layer2.setFrameShadow(QFrame.Raised)
        self.layer2.setLineWidth(1)
        self.layer2.setMidLineWidth(2)
        self.regForm = QFrame(self.layer2)
        self.regForm.setObjectName(u"regForm")
        self.regForm.setEnabled(True)
        self.regForm.setGeometry(QRect(285, 24, 256, 652))
        self.regForm.setAutoFillBackground(False)
        self.regForm.setStyleSheet(u"background-color: rgb(179, 176, 87);\n"
"color: rgb(2, 2, 2);")
        self.regForm.setFrameShape(QFrame.StyledPanel)
        self.regForm.setFrameShadow(QFrame.Raised)
        self.groupBox = QGroupBox(self.regForm)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(9, 63, 232, 292))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(93, 39, 130, 25))
        self.lineEdit_2.setStyleSheet(u"color: rgb(8, 8, 8);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(93, 75, 130, 25))
        self.lineEdit_3.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(93, 111, 130, 25))
        self.lineEdit_4.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(93, 147, 130, 25))
        self.lineEdit_5.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_6 = QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(93, 183, 130, 25))
        self.lineEdit_6.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_7 = QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(114, 219, 109, 25))
        self.lineEdit_7.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_8 = QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(93, 255, 130, 25))
        self.lineEdit_8.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(9, 45, 76, 16))
        font1 = QFont()
        font1.setPointSize(7)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(9, 78, 76, 16))
        self.label_3.setFont(font1)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(12, 153, 76, 16))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(12, 186, 76, 16))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(12, 258, 76, 16))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(9, 114, 76, 16))
        self.label_8.setFont(font1)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(12, 222, 82, 16))
        self.label_4.setFont(font1)
        self.groupBox_2 = QGroupBox(self.regForm)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(9, 381, 235, 133))
        self.groupBox_2.setFont(font)
        self.lineEdit_9 = QLineEdit(self.groupBox_2)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(102, 36, 118, 25))
        self.lineEdit_9.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_10 = QLineEdit(self.groupBox_2)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(102, 90, 118, 25))
        self.lineEdit_10.setStyleSheet(u"color: rgb(9, 9, 9);\n"
"background-color: rgb(255, 255, 255);")
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(6, 39, 82, 16))
        self.label_9.setFont(font1)
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(9, 93, 82, 16))
        self.label_10.setFont(font1)
        self.frame_3 = QFrame(self.regForm)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(9, 531, 235, 109))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(136, 81, 91, 22))
        self.pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"border-color: rgb(8, 8, 8);")
        self.pushButton.setFlat(False)
        self.pushButton_2 = QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(9, 81, 91, 22))
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(u"border-color: rgb(8, 8, 8);")
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(12, 24, 94, 22))
        self.label.setFont(font1)
        self.lineEdit = QLineEdit(self.frame_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(96, 24, 130, 28))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet(u"color: rgb(11, 11, 11);\n"
"background-color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.regForm)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(48, 9, 157, 37))
        self.label_11.setFont(font)
        self.frame_2 = QFrame(self.layer2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(15, 177, 250, 316))
        self.frame_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(6)
        self.frame_4 = QFrame(self.frame_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(15, 18, 220, 280))
        self.frame_4.setFrameShape(QFrame.Panel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setLineWidth(11)
        self.imgView = QLabel(self.layer2)
        self.imgView.setObjectName(u"imgView")
        self.imgView.setGeometry(QRect(51, 216, 178, 235))
        self.imgView.setCursor(QCursor(Qt.BlankCursor))
        self.imgView.setFrameShape(QFrame.Box)
        self.imgView.setLineWidth(4)
        self.imgView.setPixmap(QPixmap(u"photos/pic.jpg"))
        self.imgView.setScaledContents(True)
        self.loginForm = QFrame(self.layer2)
        self.loginForm.setObjectName(u"loginForm")
        self.loginForm.setGeometry(QRect(285, 225, 256, 226))
        self.loginForm.setFrameShape(QFrame.StyledPanel)
        self.loginForm.setFrameShadow(QFrame.Raised)
        self.frame_7 = QFrame(self.loginForm)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(9, 9, 238, 208))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_19 = QLabel(self.frame_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(12, 45, 73, 19))
        self.label_19.setFont(font1)
        self.username_5 = QLineEdit(self.frame_7)
        self.username_5.setObjectName(u"username_5")
        self.username_5.setGeometry(QRect(96, 42, 136, 28))
        self.username_6 = QLineEdit(self.frame_7)
        self.username_6.setObjectName(u"username_6")
        self.username_6.setGeometry(QRect(96, 90, 136, 28))
        self.label_20 = QLabel(self.frame_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(15, 90, 73, 19))
        self.label_20.setFont(font1)
        self.regButton_3 = QPushButton(self.frame_7)
        self.regButton_3.setObjectName(u"regButton_3")
        self.regButton_3.setGeometry(QRect(6, 180, 175, 19))
        self.regButton_3.setFont(font1)
        self.regButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.regButton_3.setFlat(True)
        self.loginButton_3 = QCommandLinkButton(self.frame_7)
        self.loginButton_3.setObjectName(u"loginButton_3")
        self.loginButton_3.setGeometry(QRect(138, 138, 91, 37))
        font2 = QFont()
        font2.setFamily(u"Comic Sans MS")
        self.loginButton_3.setFont(font2)
        self.loginButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.loginButton_3.setAutoFillBackground(False)
        self.loginButton_3.setStyleSheet(u"border-color: rgb(6, 6, 6);")
        self.label_21 = QLabel(self.frame_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(87, 9, 103, 22))
        self.label_21.setFont(font2)
        self.label_21.setCursor(QCursor(Qt.BlankCursor))
        self.closeDialog = QPushButton(self.layer1)
        self.closeDialog.setObjectName(u"closeDialog")
        self.closeDialog.setGeometry(QRect(526, 9, 34, 19))
        font3 = QFont()
        font3.setPointSize(11)
        self.closeDialog.setFont(font3)
        self.closeDialog.setMouseTracking(True)
        self.closeDialog.setTabletTracking(True)
        self.closeDialog.setAutoFillBackground(False)
        self.closeDialog.setStyleSheet(u"color: rgb(198, 1, 14);\n"
"border-color: rgb(9, 9, 9);")
        self.closeDialog.setFlat(True)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Personal Details", None))
        self.lineEdit_2.setText("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"First Name:*", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Surname:*", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Job Title:*", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Department:*", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Rank:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Gender:", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Employment ID:*", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Login Details", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"User ID/Name:*", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Password:*", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Register", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Authorized ID:", None))
        self.lineEdit.setText("")
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Employee Registration Form", None))
        self.imgView.setText("")
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Username/ID:", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Password:", None))
        self.regButton_3.setText(QCoreApplication.translate("Dialog", u"Register New Employee", None))
        self.loginButton_3.setText(QCoreApplication.translate("Dialog", u"Login", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Login", None))
        self.closeDialog.setText(QCoreApplication.translate("Dialog", u"X", None))
    # retranslateUi

